theme: jekyll-theme-slate
title: Peter Thompson
email: peter.thompson2881@gmail.com
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
github_username: petethegreat
linkedin_username: peter-thompson-toronto
google_analytics: UA-100872740-1
google_adsense: ca-pub-7515546376987405
github_url: https://github.com/petethegreat